// Auth tables generated by Better Auth CLI — see Task 2
// Run: npx @better-auth/cli@latest generate
// Then: npx drizzle-kit generate && npx drizzle-kit migrate
// This file will be replaced with the generated auth schema in Task 2.

export {};
