// Generated by Better Auth CLI (drizzle + pg provider)
// Run migrations: npx drizzle-kit generate && npx drizzle-kit migrate
import { boolean, integer, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
  // admin plugin fields
  role: text("role"),
  banned: boolean("banned"),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
  phoneNumber: text("phone_number"),
  // customer fields
  firstName: text("first_name"),
  lastName: text("last_name"),
  lastAppointment: timestamp("last_appointment"),
  // billing address (nullable; populated at signup, claim, or via address gate)
  postalCode: text("postal_code"),
  city: text("city"),
  streetAddress: text("street_address"),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  // admin plugin field
  impersonatedBy: text("impersonated_by"),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
});

export const cronRunLog = pgTable("cron_run_log", {
  id: text("id").primaryKey(), // crypto.randomUUID()
  runAt: timestamp("run_at").notNull(),
  remindersAttempted: integer("reminders_attempted").notNull().default(0),
  remindersSucceeded: integer("reminders_succeeded").notNull().default(0),
  remindersFailed: integer("reminders_failed").notNull().default(0),
  errorDetails: text("error_details"), // JSON string of per-email errors
  durationMs: integer("duration_ms"),
});

// Historical bookings table (migrated from Sanity to save document quota)
export const bookingHistory = pgTable("booking_history", {
  id: text("id").primaryKey(), // Original Sanity _id
  patientId: text("patient_id"), // Reference to Sanity patient _id
  patientEmail: text("patient_email"),
  patientName: text("patient_name"),
  serviceId: text("service_id"), // Reference to Sanity service _id
  serviceName: text("service_name"),
  date: text("date").notNull(), // YYYY-MM-DD
  time: text("time").notNull(), // HH:mm
  status: text("status").notNull(), // completed, cancelled, no-show
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull(),
  migratedAt: timestamp("migrated_at").notNull().defaultNow(),
});
