/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema definitions (derived from Sanity schema types)
// Generated: 2026-02-19

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityReference<T = unknown> = {
  _type: "reference";
  _ref: string;
  _weak?: boolean;
  _strengthenOnPublish?: {
    type: string;
    weak?: boolean;
    template?: {
      id: string;
      params?: Record<string, string | number | boolean>;
    };
  };
} & { _referenced?: T };

export type SanityImageAsset = {
  _type: "sanity.imageAsset";
  _id: string;
  url?: string;
  path?: string;
  assetId?: string;
  extension?: string;
  mimeType?: string;
  sha1hash?: string;
  size?: number;
  originalFilename?: string;
  metadata?: {
    _type: "sanity.imageMetadata";
    dimensions?: {
      _type: "sanity.imageDimensions";
      height?: number;
      width?: number;
      aspectRatio?: number;
    };
    lqip?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
  };
};

export type SanityImageObject = {
  _type: "image";
  asset?: SanityReference<SanityImageAsset>;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

// ─── Document Types ───────────────────────────────────────────────────────────

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeadline?: string;
  heroSubtitle?: string;
  heroBadges?: Array<{
    _key: string;
    emoji?: string;
    text?: string;
  }>;
  heroDoctorImage?: SanityImageObject;
  heroCards?: Array<{
    _key: string;
    title?: string;
    subtitle?: string;
    icon?: SanityImageObject;
  }>;
  servicesHeadline?: string;
  servicesSubtitle?: string;
  labTestsHeadline?: string;
  labTestsSubtitle?: string;
  testimonialsHeadline?: string; testimonialsCtaText?: string; testimonialsCtaUrl?: string; testimonials?: Array<{ _id: string; patientName?: string; photo?: SanityImageObject; text?: string; condition?: string; order?: number; }>;
  blogHeadline?: string;
  ctaHeadline?: string;
  ctaDescription?: string;
  metaDescription?: string;
  ogImage?: SanityImageObject;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: SanityImageObject;
  clinicName?: string;
  phone?: string;
  email?: string;
  address?: string;
  navigationLinks?: Array<{
    _key: string;
    label?: string;
    href?: string;
  }>;
  socialLinks?: Array<{
    _key: string;
    platform?: "facebook" | "instagram" | "linkedin" | "youtube" | "tiktok";
    url?: string;
  }>;
  footerColumns?: Array<{
    _key: string;
    heading?: string;
    links?: Array<{
      _key: string;
      label?: string;
      href?: string;
    }>;
  }>;
  privacyPolicyUrl?: string;
  metaDescription?: string;
  siteName?: string;
  defaultOgImage?: SanityImageObject;
};

export type ServiceCategory = {
  _id: string;
  _type: "serviceCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  emoji?: string;
  order?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  price?: number;
  icon?: SanityImageObject;
  category?: SanityReference<ServiceCategory>;
  order?: number;
  appointmentDuration?: 10 | 15 | 20 | 30 | 45 | 60;
};

export type LabTest = {
  _id: string;
  _type: "labTest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  price?: number;
  originalPrice?: number;
  discount?: number;
  illustration?: SanityImageObject;
  body?: PortableTextBlock[];
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  patientName?: string;
  photo?: SanityImageObject;
  text?: string;
  condition?: string;
  order?: number;
};

export type BlogCategory = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  order?: number;
};

export type PortableTextSpan = {
  _type: "span";
  _key: string;
  text?: string;
  marks?: string[];
};

export type PortableTextMarkDefLink = {
  _type: "link";
  _key: string;
  href?: string;
};

export type PortableTextBlock = {
  _type: "block";
  _key: string;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  children?: PortableTextSpan[];
  markDefs?: PortableTextMarkDefLink[];
};

export type BlogPostBodyImage = SanityImageObject & {
  _key: string;
  alt?: string;
  caption?: string;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: SanityReference<BlogCategory>;
  featuredImage?: SanityImageObject;
  excerpt?: string;
  body?: Array<PortableTextBlock | BlogPostBodyImage>;
  metaDescription?: string;
  ogImage?: SanityImageObject;
  publishedAt?: string;
};

export type PrivacyPolicy = {
  _type: "privacyPolicy";
  _id: string;
  title?: string;
  body?: Array<PortableTextBlock | BlogPostBodyImage>;
  lastUpdated?: string;
};

// Weekly schedule day configuration
export type WeeklyScheduleDay = {
  _key: string;
  dayOfWeek: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  isDayOff: boolean;
  startTime?: string;
  endTime?: string;
};

export type WeeklySchedule = {
  _type: "weeklySchedule";
  _id: string;
  defaultSlotDuration: 10 | 15 | 20 | 30 | 45 | 60;
  bufferMinutes: number;
  days: WeeklyScheduleDay[];
};

// Blocked date entry
export type BlockedDateEntry = {
  _key: string;
  date: string;
  isHoliday: boolean;
};

export type BlockedDate = {
  _type: "blockedDate";
  _id: string;
  dates: BlockedDateEntry[];
};

// ─── All Document Types Union ─────────────────────────────────────────────────

// ─── Booking ──────────────────────────────────────────────────────────────────

export type Booking = {
  _type: "booking";
  _id: string;
  service?: SanityReference;
  slotDate?: string;
  slotTime?: string;
  patientName?: string;
  patientEmail?: string;
  patientPhone?: string;
  reservationNumber?: string;
  managementToken?: string;
  userId?: string;
  status?: "confirmed" | "cancelled" | "rescheduled";
  createdAt?: string;
  reminderSent?: boolean;
};

// ─── Slot Lock ────────────────────────────────────────────────────────────────

export type SlotLock = {
  _type: "slotLock";
  _id: string;
  slotId?: string;
  status?: "available" | "held" | "booked";
  heldUntil?: string;
  bookingRef?: SanityReference;
};

export type AllSanitySchemaTypes =
  | Homepage
  | SiteSettings
  | ServiceCategory
  | Service
  | LabTest
  | Testimonial
  | BlogCategory
  | BlogPost
  | PrivacyPolicy
  | WeeklySchedule
  | BlockedDate
  | Booking
  | SlotLock;

// ─── Query Result Types ───────────────────────────────────────────────────────
// These types match the shape returned by GROQ queries that dereference references inline.

export type ServiceQueryResult = {
  _id: string;
  name?: string;
  description?: string;
  price?: number;
  icon?: SanityImageObject;
  category?: { _id: string; name?: string; emoji?: string };
  order?: number;
  appointmentDuration?: 10 | 15 | 20 | 30 | 45 | 60;
};

export type ServiceCategoryQueryResult = {
  _id: string;
  name?: string;
  emoji?: string;
  order?: number;
};

export type LabTestQueryResult = {
  _id: string;
  name?: string;
  slug?: Slug;
  description?: string;
  price?: number;
  originalPrice?: number;
  discount?: number;
  illustration?: SanityImageObject;
  order?: number;
};

export type LabTestDetailResult = {
  _id: string;
  name?: string;
  slug?: Slug;
  description?: string;
  price?: number;
  originalPrice?: number;
  discount?: number;
  illustration?: SanityImageObject;
  body?: PortableTextBlock[];
  order?: number;
};

export type TestimonialQueryResult = {
  _id: string;
  patientName?: string;
  photo?: SanityImageObject;
  text?: string;
  condition?: string;
  order?: number;
};

export type BlogPostQueryResult = {
  _id: string;
  title?: string;
  slug?: Slug;
  category?: { _id: string; name?: string };
  featuredImage?: SanityImageObject;
  excerpt?: string;
};

export type BlogPostDetailResult = {
  _id: string;
  title?: string;
  slug?: Slug;
  category?: { _id: string; name?: string; slug?: Slug };
  featuredImage?: SanityImageObject;
  body?: Array<PortableTextBlock | BlogPostBodyImage>;
  excerpt?: string;
  metaDescription?: string;
  ogImage?: SanityImageObject;
  publishedAt?: string;
};

// ─── Booking Query Result Types ───────────────────────────────────────────────

export type BookingsForDateQueryResult = Array<{
  _id: string;
  slotTime?: string;
  service?: { _id: string; appointmentDuration?: number } | null;
}>;

export type SlotLocksForDateQueryResult = Array<{
  _id: string;
  _rev: string;
  slotId?: string;
  status?: "available" | "held" | "booked";
  heldUntil?: string | null;
}>;

export type SlotLockByIdQueryResult = {
  _id: string;
  _rev: string;
  status?: "available" | "held" | "booked";
  heldUntil?: string | null;
} | null;

export type ServicesForBookingQueryResult = Array<{
  _id: string;
  name?: string;
  appointmentDuration?: number;
  icon?: SanityImageObject;
}>;

